org.gradle.jvmargs=-Xmx2048M -Xms512M -XX:MaxPermSize=512M -XX:MaxMetaspaceSize=1G -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.caching=true
android.useAndroidX=true
android.enableJetifier=true
android.enableR8=true
android.nonTransitiveRClass=false
kotlin.code.style=official

